openapi: 3.0.0
info:
  title: 'Search API'
  version: 1.0.0
paths:
  /start/create-user:
    post:
      tags:
        - Post
      summary: 'Create a new user.'
      operationId: 'taskGateway::CreateUser'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: integer
                  example: '4'
                date_entered:
                  type: varchar
                  example: '11'
                shop_id:
                  type: integer
                  example: '1'
                username:
                  type: varchar
                  example: mirko43
                password:
                  type: varchar
                  example: Test0011
                type:
                  type: varchar
                  example: test
                status:
                  type: varchar
                  example: activ
              type: object
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
  /start/create-shop:
    post:
      tags:
        - Post
      summary: 'Create a shop.'
      operationId: 'taskGateway::CreateShop'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: integer
                  example: '1'
                date_entered:
                  type: varchar
                  example: '11'
                name:
                  type: string
                  example: nameofshop
                email:
                  type: varchar
                  example: mirko43@test.com
                status:
                  type: varchar
                  example: activ
              type: object
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
  /start/create-transaction:
    post:
      tags:
        - Post
      summary: 'Create a transaction.'
      operationId: 'taskGateway::CreateTransaction'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: integer
                  example: '4'
                date_entered:
                  type: varchar
                  example: '11'
                shop_id:
                  type: integer
                  example: '1'
                barcode:
                  type: integer
                  example: '1216361346'
                type:
                  type: varchar
                  example: test
                amount:
                  type: integer
                  example: '255'
                start_amount:
                  type: integer
                  example: '10'
                end_amount:
                  type: integer
                  example: '2000'
                comment:
                  type: string
                  example: 'This is comment'
              type: object
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
  /start/create-card:
    post:
      tags:
        - Post
      summary: 'Create a card.'
      operationId: 'taskGateway::CreateCard'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: integer
                  example: '4'
                date_entered:
                  type: varchar
                  example: '11'
                barcode:
                  type: integer
                  example: '322423423'
                amount:
                  type: integer
                  example: '500'
                last_payment:
                  type: varchar
                  example: '1.1'
                status:
                  type: type
                  example: test
              type: object
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
  /start/all-transaction:
    post:
      tags:
        - Post
      summary: 'Get all transaction'
      operationId: 'taskGateway::allTransaction'
      requestBody:
        content:
          application/json:
            schema:
              required:
                - id
              properties:
                id:
                  type: integer
              type: object
      responses:
        '200':
          description: 'An example resource'
        '404':
          description: 'Not Found'
  /start/amount-transaction:
    get:
      tags:
        - Get
      summary: 'Get amount for transaction'
      operationId: 'taskGateway::amountAndTransaction'
      responses:
        '200':
          description: Success
        '404':
          description: 'Not found'
  /start/supplement-card:
    post:
      tags:
        - Post
      summary: 'Supplement the card'
      operationId: 'taskGateway::supplementCard'
      requestBody:
        content:
          application/json:
            schema:
              required:
                - amount
              properties:
                amount:
                  type: integer
              type: object
      responses:
        '200':
          description: 'An example resource'
        '404':
          description: 'Not Found'
  /start/login:
    post:
      tags:
        - Post
      summary: Login
      operationId: 'taskGateway::login'
      requestBody:
        content:
          application/json:
            schema:
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
              type: object
      responses:
        '200':
          description: 'An example resource'
        '404':
          description: 'Not Found'
